/*
 *
 *
 * Created:        Tuesday, March 23, 2021 10:50:14 PM
 * Description:    8_Compressor_RMS:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2021 Analog Devices, Inc. All rights reserved.
 */
#ifndef __8_COMPRESSOR_RMS_IC_1_PARAM_H__
#define __8_COMPRESSOR_RMS_IC_1_PARAM_H__


/* Module Compressor - RMS (gain)*/
#define MOD_COMPRESSOR_COUNT                           38
#define MOD_COMPRESSOR_DEVICE                          "IC1"
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX20_ADDR 0
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX20_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX20_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX20_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX21_ADDR 1
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX21_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX21_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX21_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX22_ADDR 2
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX22_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX22_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX22_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX23_ADDR 3
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX23_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX23_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX23_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX24_ADDR 4
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX24_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX24_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX24_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX25_ADDR 5
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX25_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX25_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX25_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX26_ADDR 6
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX26_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX26_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX26_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX27_ADDR 7
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX27_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX27_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX27_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX28_ADDR 8
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX28_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX28_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX28_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX29_ADDR 9
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX29_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX29_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX29_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX210_ADDR 10
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX210_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX210_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX210_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX211_ADDR 11
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX211_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX211_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX211_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX212_ADDR 12
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX212_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX212_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX212_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX213_ADDR 13
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX213_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX213_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX213_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX214_ADDR 14
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX214_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX214_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX214_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX215_ADDR 15
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX215_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX215_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX215_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX216_ADDR 16
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX216_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX216_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX216_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX217_ADDR 17
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX217_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX217_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX217_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX218_ADDR 18
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX218_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX218_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX218_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX219_ADDR 19
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX219_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX219_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX219_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX220_ADDR 20
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX220_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX220_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX220_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX221_ADDR 21
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX221_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX221_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX221_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX222_ADDR 22
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX222_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX222_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX222_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX223_ADDR 23
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX223_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX223_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX223_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX224_ADDR 24
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX224_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX224_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX224_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX225_ADDR 25
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX225_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX225_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX225_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX226_ADDR 26
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX226_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX226_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX226_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX227_ADDR 27
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX227_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX227_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX227_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX228_ADDR 28
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX228_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX228_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX228_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX229_ADDR 29
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX229_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX229_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX229_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX230_ADDR 30
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX230_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX230_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX230_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX231_ADDR 31
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX231_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX231_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX231_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX232_ADDR 32
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX232_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX232_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX232_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX233_ADDR 33
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX233_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX233_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX233_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2RMS_ADDR 34
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2RMS_FIXPT 0x000012DE
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000575811989360853)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2RMS_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2POSTGAIN_ADDR 35
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2POSTGAIN_FIXPT 0x00800000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2POSTGAIN_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2POSTGAIN_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2HOLD_ADDR 36
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2HOLD_FIXPT 0x00000000
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2DECAY_ADDR 37
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2DECAY_FIXPT 0x00000012
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(2.17013888888889E-06)
#define MOD_COMPRESSOR_ALG0_TWOCHANNELSINGLEDETECTALGFIX2DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Bypass - Stereo Switch Nx2*/
#define MOD_BYPASS_COUNT                               1
#define MOD_BYPASS_DEVICE                              "IC1"
#define MOD_BYPASS_STEREOSWSLEW_ADDR                   38
#define MOD_BYPASS_STEREOSWSLEW_FIXPT                  0x00000000
#define MOD_BYPASS_STEREOSWSLEW_VALUE                  SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_BYPASS_STEREOSWSLEW_TYPE                   SIGMASTUDIOTYPE_INTEGER

/* Module SW vol 1 - Single SW slew vol (adjustable)*/
#define MOD_SWVOL1_COUNT                               2
#define MOD_SWVOL1_DEVICE                              "IC1"
#define MOD_SWVOL1_ALG0_TARGET_ADDR                    39
#define MOD_SWVOL1_ALG0_TARGET_FIXPT                   0x00800000
#define MOD_SWVOL1_ALG0_TARGET_VALUE                   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SWVOL1_ALG0_TARGET_TYPE                    SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SWVOL1_ALG0_STEP_ADDR                      40
#define MOD_SWVOL1_ALG0_STEP_FIXPT                     0x00000800
#define MOD_SWVOL1_ALG0_STEP_VALUE                     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000244140625)
#define MOD_SWVOL1_ALG0_STEP_TYPE                      SIGMASTUDIOTYPE_FIXPOINT

#endif
